Remove ffmpeg ghost process when celery task is cancelled
testpress/lumberjack pull request #15
Opened 2020-10-26 08:27 UTC by Karthik-0

- When a celery task is revoked, the FFmpeg process that is started by celery is not getting killed.
- This wastes resources as we don't need those cancelled FFmpeg processes to be running.
- Solution is to kill celery we should trigger "SIGUSR1". "SIGUSR1" signal will raise SoftTimeLimitExceeded exception. We should perform FFmpeg process cleanup in SoftTimeLimitExceeded exception handler.

2020-10-26 09:32 UTC, waranlogesh requested changes

2020-10-26 09:32 UTC, waranlogesh commented on lumberjack/apps/jobs/runnables.py
> +        self.ffmpeg_manager = Manager(self.output.settings, self.update_progress)
Adding a new instance variable buried in some class method is not straight forward. Instead, you could add a temporal coupling between `start_transcoding()` and `stop_process()`. 

In this implementaion, we have hidden temporal coupling
<img width="705" alt="hidden_temporal_coupling" src="https://user-images.githubusercontent.com/9105503/97155482-711c9380-179b-11eb-99f1-9dfc202b5021.png">

You check the full explanation of the above in the clean code for better understanding.

2020-10-26 09:32 UTC, waranlogesh commented on lumberjack/apps/jobs/runnables.py
> +            if task.id != self.task_id:  # Skip killing current task as it is going to be stopped anyway.
This doesn't look right. Isn't `SIGUSR1` no-op?

If the current task is killed properly then why isn't the child tasks killed properly. This should be the default celery behaviour right?

2020-10-26 09:37 UTC, Karthik-0 commented on lumberjack/apps/jobs/runnables.py
> +            if task.id != self.task_id:  # Skip killing current task as it is going to be stopped anyway.
This doesn't look right. Isn't SIGUSR1 no-op?
- SIGUSR1 is a user-defined signal provided by Linux. Celery will raise `SoftTimeLimitExceeded` exception.

If the current task is killed properly then why isn't the child tasks killed properly. This should be the default celery behavior right?
- For a single job, 4 tasks will run(assuming one video has to be transcoded into 4 resolutions). Now if one of the tasks got an error, the other 3 should get stopped. For that, we will get all 4 tasks and then stop 3 running tasks.

2020-10-28 08:32 UTC, bharathwaaj approved these changes

2020-10-28 08:32 UTC, merged